# Generated by Django 5.0.6 on 2024-07-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veggi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipie',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
